import { describe, expect, test } from 'vitest';
import type { IssueIF } from '../../model/Issue/IssueIF';
import type { ProjectIF } from '../../model/ProjectIF';
import type { EmployeeIF } from '../../model/EmployeeIF';
import { calculateAverageRestingTime, getAssigneeCountFromIssues } from '../assigneeCardCalculator';

const testProject: ProjectIF = {
  id: 1,
  name: 'testProject',
  description: 'testProject',
  issues: [
    {
      id: 1,
      name: '1',
      description: null,
      priority: null,
      issueType: null,
      assignedTo: {
        id: 1,
        firstName: 'firstName_1',
        lastName: 'lastName_1',
        emailAddress: '0',
        avatarUrl: '0',
        status: 'active',
        key: '0',
      } as EmployeeIF,
      createdBy: null,
      createdAt: null,
      closedAt: null,
      dueTo: null,
      status: null,
      statusChanges: [],
      lastStatusChange: null,
      assigneeRestingTime: {
        weeks: 0,
        days: 1,
        hours: 4,
        minutes: 0,
        seconds: 0,
        milliseconds: 0,
      },
      assigneeChanges: null,
      statusRestingTime: null,
      state: null,
      changelog: null,
    } as IssueIF,
    {
      id: 2,
      name: '2',
      description: null,
      priority: null,
      issueType: null,
      assignedTo: {
        id: 2,
        firstName: 'firstName_2',
        lastName: 'lastName_2',
        emailAddress: '1',
        avatarUrl: '1',
        status: 'active',
        key: '1',
      } as EmployeeIF,
      createdBy: null,
      createdAt: null,
      closedAt: null,
      dueTo: null,
      status: null,
      statusChanges: [],
      lastStatusChange: null,
      assigneeRestingTime: {
        weeks: 0,
        days: 1,
        hours: 4,
        minutes: 0,
        seconds: 0,
        milliseconds: 0,
      },
      assigneeChanges: null,
      statusRestingTime: null,
      state: null,
      changelog: null,
    } as IssueIF,
    {
      id: 3,
      name: '3',
      description: null,
      issueType: null,
      priority: null,
      assignedTo: {
        id: 3,
        firstName: 'firstName_3',
        lastName: 'lastName_3',
        emailAddress: '2',
        avatarUrl: '2',
        status: 'active',
        key: '2',
      } as EmployeeIF,
      createdBy: null,
      createdAt: null,
      closedAt: null,
      dueTo: null,
      status: null,
      statusChanges: [],
      lastStatusChange: null,
      assigneeRestingTime: {
        weeks: 0,
        days: 1,
        hours: 4,
        minutes: 0,
        seconds: 0,
        milliseconds: 0,
      },
      assigneeChanges: null,
      statusRestingTime: null,
      state: null,
      changelog: null,
    } as IssueIF,
    {
      id: 4,
      name: '4',
      description: null,
      issueType: null,
      priority: null,
      assignedTo: {
        id: 4,
        firstName: 'firstName_4',
        lastName: 'lastName_4',
        emailAddress: '3',
        avatarUrl: '3',
        status: 'active',
        key: '3',
      } as EmployeeIF,
      createdBy: null,
      createdAt: null,
      closedAt: null,
      dueTo: null,
      status: null,
      statusChanges: [],
      lastStatusChange: null,
      assigneeRestingTime: {
        weeks: 0,
        days: 1,
        hours: 4,
        minutes: 0,
        seconds: 0,
        milliseconds: 0,
      },
      assigneeChanges: null,
      statusRestingTime: null,
      state: null,
      changelog: null,
    } as IssueIF,
    {
      id: 5,
      name: '5',
      description: null,
      issueType: null,
      priority: null,
      assignedTo: {
        id: 5,
        firstName: 'firstName_5',
        lastName: 'lastName_5',
        emailAddress: '4',
        avatarUrl: '4',
        status: 'active',
        key: '4',
      } as EmployeeIF,
      createdBy: null,
      createdAt: null,
      closedAt: null,
      dueTo: null,
      status: null,
      statusChanges: [],
      lastStatusChange: null,
      assigneeRestingTime: {
        weeks: 0,
        days: 1,
        hours: 4,
        minutes: 0,
        seconds: 0,
        milliseconds: 0,
      },
      assigneeChanges: null,
      statusRestingTime: null,
      state: null,
      changelog: null,
    } as IssueIF,
    {
      id: 6,
      name: '6',
      description: null,
      issueType: null,
      priority: null,
      assignedTo: {
        id: 6,
        firstName: 'firstName_6',
        lastName: 'lastName_6',
        emailAddress: '5',
        avatarUrl: '5',
        status: 'active',
        key: '5',
      } as EmployeeIF,
      createdBy: null,
      createdAt: null,
      closedAt: null,
      dueTo: null,
      status: null,
      statusChanges: [],
      lastStatusChange: null,
      assigneeRestingTime: {
        weeks: 0,
        days: 1,
        hours: 4,
        minutes: 0,
        seconds: 0,
        milliseconds: 0,
      },
      assigneeChanges: null,
      statusRestingTime: null,
      state: null,
      changelog: null,
    } as IssueIF,
  ],
};

describe('assigneeCardCalculator', () => {
  test('calculateAverageRestingTime with empty issues', () => {
    expect(calculateAverageRestingTime([] as IssueIF[])).toBe(null);
  });
  test('calculateAverageRestingTime', () => {
    expect(
      calculateAverageRestingTime(testProject.issues)?.toFormat("d 'days' h 'hours'").toString()
    ).toBe('1 days 4 hours');
  });
  test('getAssigneeCountFromIssues with empty project', () => {
    expect(getAssigneeCountFromIssues({} as ProjectIF)).toBe(0);
  });
  test('getAssigneeCountFromIssues', () => {
    expect(getAssigneeCountFromIssues(testProject)).toBe(6);
  });
});
