import { describe, assert, test } from 'vitest';
import { filterProjectThatHasTheAllowedStatus } from '@/services/filter/IssuesStateFilter';
import type { FilterConfigIF } from '@/model/FilterConfigIF';
import type { ProjectIF } from '@/model/ProjectIF';

describe('filterProjectThatHasTheAllowedStatus', () => {
  test('should filter projects based on the allowed status', () => {
    const projects: ProjectIF[] = [
      {
        id: 1,
        name: 'Project 1',
        description: 'Project 1 description',
        issues: [
          {
            id: 1,
            status: 'open',
            name: 'Issue 1',
            description: 'Issue 1 description',
            priority: null,
            issueType: null,
            assignedTo: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            createdBy: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'planning',
          },
          {
            id: 3,
            status: 'in progress',
            name: 'Issue 3',
            description: 'Issue 3 description',
            issueType: null,
            priority: null,
            assignedTo: {
              id: 6,
              firstName: 'Gabi',
              lastName: 'Winkler',
              emailAddress: 'gabi.winkler@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'gwinkler',
            },
            createdBy: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'development',
          },
        ],
      },
      {
        id: 2,
        name: 'Project 2',
        description: 'Project 2 description',
        issues: [
          {
            id: 5,
            status: 'open',
            name: 'Issue 5',
            description: 'Issue 5 description',
            priority: null,
            issueType: null,
            assignedTo: {
              id: 7,
              firstName: 'Franzi',
              lastName: 'Siemens',
              emailAddress: 'franzi.siemens@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'fsiemens',
            },
            createdBy: {
              id: 8,
              firstName: 'Helmut',
              lastName: 'Freiherr',
              emailAddress: 'helmut.freiherr@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'hfreiherr',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'planning',
          },
          {
            id: 3,
            status: 'in progress',
            name: 'Issue 3',
            description: 'Issue 3 description',
            issueType: null,
            priority: null,
            assignedTo: {
              id: 6,
              firstName: 'Gabi',
              lastName: 'Winkler',
              emailAddress: 'gabi.winkler@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'gwinkler',
            },
            createdBy: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'development',
          },
        ],
      },
    ];

    const filterConfig: FilterConfigIF = {
      id: 4,
      projectFilter: {
        projectsWhiteList: projects,
        issueStatusIncludeFilter: ['open', 'in progress'],
        minimumAssigneeRestingTime: 0,
        minimumNumberOfStatusChanges: 0,
        issueStateIncludeFilter: ['planning', 'development', 'testing'],
        minimumStatusRestingTime: 0,
      },
    };

    const filteredProjects = filterProjectThatHasTheAllowedStatus(filterConfig);
    assert.deepStrictEqual(filteredProjects, [
      {
        id: 1,
        name: 'Project 1',
        description: 'Project 1 description',
        issues: [
          {
            id: 1,
            status: 'open',
            name: 'Issue 1',
            description: 'Issue 1 description',
            priority: null,
            issueType: null,
            assignedTo: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            createdBy: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'planning',
          },
          {
            id: 3,
            status: 'in progress',
            name: 'Issue 3',
            description: 'Issue 3 description',
            issueType: null,
            priority: null,
            assignedTo: {
              id: 6,
              firstName: 'Gabi',
              lastName: 'Winkler',
              emailAddress: 'gabi.winkler@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'gwinkler',
            },
            createdBy: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'development',
          },
        ],
      },
      {
        id: 2,
        name: 'Project 2',
        description: 'Project 2 description',
        issues: [
          {
            id: 5,
            status: 'open',
            name: 'Issue 5',
            description: 'Issue 5 description',
            issueType: null,
            priority: null,
            assignedTo: {
              id: 7,
              firstName: 'Franzi',
              lastName: 'Siemens',
              emailAddress: 'franzi.siemens@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'fsiemens',
            },
            createdBy: {
              id: 8,
              firstName: 'Helmut',
              lastName: 'Freiherr',
              emailAddress: 'helmut.freiherr@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'hfreiherr',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'planning',
          },
          {
            id: 3,
            status: 'in progress',
            name: 'Issue 3',
            description: 'Issue 3 description',
            issueType: null,
            priority: null,
            assignedTo: {
              id: 6,
              firstName: 'Gabi',
              lastName: 'Winkler',
              emailAddress: 'gabi.winkler@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'gwinkler',
            },
            createdBy: {
              id: 4,
              firstName: 'Bernd',
              lastName: 'Mustermann',
              emailAddress: 'bern.mustermann@email.com',
              status: 'active',
              avatarUrl: 'none',
              key: 'bmustermann',
            },
            dueTo: new Date('2021-01-01'),
            createdAt: new Date('2021-01-01'),
            closedAt: new Date('2021-01-02'),
            assigneeRestingTime: null,
            statusRestingTime: null,
            assigneeChanges: [],
            statusChanges: [],
            state: 'development',
          },
        ],
      },
    ]);
  });
});
